//Date: 12/05/2012 16:58:49
//Template version 1.1
//Java generated by Techne
//Keep in mind that you still need to fill in some blanks
//- ZeuX






package net.minecraft.src;

public class Model_slab extends ModelBase
{
//fields
  ModelRenderer slab;

public Model_slab()
{
    this(0.0F);
}
  
public Model_slab(float par1)
{
  textureWidth = 64;
  textureHeight = 32;
  
    slab = new ModelRenderer(this, 0, 32);
    slab.addBox(0F, 0F, 0F, 15, 8, 15, par1);
    slab.setRotationPoint(-7.5F, 16F, -7.5F);
    slab.setTextureSize(64, 32);
    slab.mirror = true;
    setRotation(slab, 0F, 0F, 0F);
}

public void renderModel(float f)
{
      slab.render(f);
}

public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
{
  super.render(entity, f, f1, f2, f3, f4, f5);
  setRotationAngles(f, f1, f2, f3, f4, f5);
  slab.render(f5);
}

private void setRotation(ModelRenderer model, float x, float y, float z)
{
  model.rotateAngleX = x;
  model.rotateAngleY = y;
  model.rotateAngleZ = z;
}

public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
{
  super.setRotationAngles(f, f1, f2, f3, f4, f5);
}

}
